version: '3.8'

services:
  atlas:
    image: apache/atlas:latest
    container_name: atlas
    ports:
      - "21000:21000"
    environment:
      - ATLAS_OPTS=-Xmx1024m -Xms512m
      - ATLAS_HOME=/opt/apache-atlas
      - ATLAS_LOG_DIR=/opt/apache-atlas/logs
      - ATLAS_PID_DIR=/opt/apache-atlas/logs
      - ATLAS_EXPANDED_WEBAPP_DIR=/opt/apache-atlas/server/webapp
      - ATLAS_DATA=/opt/apache-atlas/data
    volumes:
      - atlas_data:/opt/apache-atlas/data
      - atlas_logs:/opt/apache-atlas/logs

  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase
    ports:
      - "16010:16010"
      - "16000:16000"
      - "2181:2181"
    environment:
      - HBASE_ROOT_LOGGER=INFO,console
    volumes:
      - hbase_data:/data/hbase

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

volumes:
  atlas_data:
  atlas_logs:
  hbase_data:
