version: '3'
services:
  spark-master:
    image: spark
    command: bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: spark
    command: bash -c "/opt/spark/sbin/start-slave.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
