services:
  mariadb:
    image: arm64v8/mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hivepassword
    volumes:
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-metastore:
    image: arm64v8/openjdk:11-jre-slim
    volumes:
      - ./hive_data:/opt/hive
      - ./hadoop_data:/opt/hadoop
    command: |
      bash -c '
      set -e
      apt-get update && apt-get install -y wget
      # ... (previous wget and extraction commands remain the same)
      echo "Waiting for MariaDB to be fully ready..."
      sleep 15
      echo "Running schematool..."
      /opt/hive/bin/schematool -dbType mysql -initSchema --verbose
      echo "Schematool completed. Starting Hive metastore..."
      /opt/hive/bin/hive --service metastore
      '
    environment:
      HADOOP_HOME: /opt/hadoop
      HIVE_CONF_javax_jdo_option_ConnectionURL: jdbc:mysql://mariadb:3306/metastore
      HIVE_CONF_javax_jdo_option_ConnectionDriverName: com.mysql.cj.jdbc.Driver
      HIVE_CONF_javax_jdo_option_ConnectionUserName: root
      HIVE_CONF_javax_jdo_option_ConnectionPassword: rootpassword
    depends_on:
      mariadb:
        condition: service_healthy

  hive-server2:
    image: arm64v8/openjdk:11-jre-slim
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./hive_data:/opt/hive
      - ./hadoop_data:/opt/hadoop
    command: >
      /bin/bash -c "
      apt-get update && apt-get install -y netcat &&
      while ! nc -z hive-metastore 9083; do sleep 1; done &&
      export HADOOP_HOME=/opt/hadoop &&
      export PATH=\$$PATH:\$$HADOOP_HOME/bin &&
      /opt/hive/bin/hiveserver2
      "
    environment:
      HADOOP_HOME: /opt/hadoop
      HIVE_CONF_javax_jdo_option_ConnectionURL: jdbc:mysql://mariadb/metastore
      HIVE_CONF_javax_jdo_option_ConnectionDriverName: com.mysql.cj.jdbc.Driver
      HIVE_CONF_javax_jdo_option_ConnectionUserName: hive
      HIVE_CONF_javax_jdo_option_ConnectionPassword: hivepassword
    depends_on:
      - hive-metastore

  beeline:
    image: arm64v8/openjdk:11-jre-slim
    volumes:
      - ./hive_data:/opt/hive
      - ./hadoop_data:/opt/hadoop
    command: >
      /bin/bash -c "
      apt-get update && apt-get install -y netcat &&
      while ! nc -z hive-server2 10000; do sleep 1; done &&
      echo 'Beeline is ready. You can now use Docker exec to run Beeline commands.'
      tail -f /dev/null
      "
    environment:
      HADOOP_HOME: /opt/hadoop
    depends_on:
      - hive-server2

volumes:
  mariadb_data:
  hive_data:
  hadoop_data: