services:
  postgres-db:
    image: postgres:13
    platform: linux/arm64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive

  hive-metastore:
    build:
      context: .
      dockerfile: Dockerfile.hive
    platform: linux/arm64
    ports:
      - "9083:9083"
    depends_on:
      - postgres-db
    command: ["metastore"]

  hive-server:
    build:
      context: .
      dockerfile: Dockerfile.hive
    platform: linux/arm64
    ports:
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - hive-metastore
    command: ["hiveserver2"]

  beeline:
    build:
      context: .
      dockerfile: Dockerfile.hive
    platform: linux/arm64
    depends_on:
      - hive-server
    entrypoint: [ "/bin/bash" ]
    command: [ "-c", "sleep infinity" ]