services:
  meta_connector:
    build:
      context: .
      dockerfile_inline: |-
        FROM docker.io/kstott/meta_connector:latest
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    env_file:
      - .env.local
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: ${HASURA_CONNECTOR_PORT:8080}
        protocol: tcp
    volumes:
      - .:/etc/connector
      - ${MODEL_FILE:-./models/model.json}:/etc/connector/model.json
