services:
  my_subgraph_calcite:
    build:
      context: .
      dockerfile_inline: |-
        FROM ndc-calcite:latest
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    env_file:
      - .env
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8084"
        protocol: tcp
    volumes:
      - /Users/kennethstott/Documents/GitHub/ndc-calcite/adapters/jdbc:/data
      - /Users/kennethstott/Documents/GitHub/ndc-calcite/adapters/jdbc/configuration.json:/app/configuration.json
