name: Docker Image CI
on:
  push:
    branches:
      - main
      - dventimihasura/add-gh-actions
    tags:
      - 'v*'
jobs:
  build:
    name: Build Connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          architecture: x64
      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2
      # - name: Build with Gradle
      #   working-directory: calcite-rs-jni/calcite
      #   run: |
      #     ./gradlew clean
      #     ./gradlew assemble
      - name: Build the Java project
        run: |
          cd calcite-rs-jni
          ./build.sh
      - name: Build with Gradle
        working-directory: calcite-rs-jni/calcite
        run: |
          ./gradlew clean
          ./gradlew assemble
      - name: Copy Maven dependencies
        working-directory: calcite-rs-jni
        run: |
          mvn clean install
          mvn dependency:copy-dependencies
      # - name: Build the Connector and CLI Plugin
      #   run: |
      #     cargo build --bin ndc-calcite --bin ndc-calcite-cli
      # - name: Build the docker image
      #   uses: docker/build-push-action@v4

          

