name: Docker Image CI
on:
  push:
    branches:
      - main
      - dventimihasura/add-gh-actions
    tags:
      - 'v*'
jobs:
  build:
    name: Build Connector
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd calcite-rs-jni
          chmod +x build.sh
          ./build.sh
          cd ..
          cargo build --bin ndc-calcite --bin ndc-calcite-cli
