name: Docker Image CI
on:
  push:
    branches:
      - main
      - dventimihasura/add-gh-actions
    tags:
      - 'v*'
jobs:
  build:
    name: Build Connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Gradle build
        # uses: gradle/gradle-build-action@v2
        working-directory: ./calcite-rs-jni/calcite
        run: ./gradlew assemble
      # - name: Maven build
      #   working-directory: calcite-rs-jni
      #   run: mvn clean install dependency:copy-dependencies
      # - name: Build the Connector and CLI Plugin
      #   run: cargo build --bin ndc-calcite --bin ndc-calcite-cli
      # - name: Build the docker image
      #   run: docker build -t ghcr.io/hasura/ndc-calcite:latest .

  # build:

  #   runs-on: ubuntu-latest

  #   steps: 
  #   - uses: actions/checkout@v3
  #   - uses: docker/setup-qemu-action@v3
  #   - uses: docker/setup-buildx-action@v3
  #   - uses: docker/build-push-action@v5
  #     with:
  #       context: .
  #       tags: ghcr.io/hasura/ndc-calcite:latest
  #       platforms: linux/amd64,linux/arm64
  #       cache-from: type=gha
  #       cache-to: type=gha,mode=max
    
